In [11]:
import pandas as pd
df = pd.read_csv(r"C:\Users\PRATHAMESH\Downloads\pokemon.csv")

In [14]:
df.head(2)

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,Weight,abilities,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate
0,0,Bulbasaur,,Grass Poison,318,45,49,49,65,65,...,6.9 kg (15.2 lbs),1. OvergrowChlorophyll (hidden ability),1 Special Attack,"45 (5.9% with PokéBall, full HP)",50 (normal),64,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)"
1,1,Ivysaur,,Grass Poison,405,60,62,63,80,80,...,13.0 kg (28.7 lbs),1. OvergrowChlorophyll (hidden ability),"1 Special Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),142,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)"

In [16]:
df.shape

(1045, 23)

In [18]:
df.columns.tolist()

['Unnamed: 0',
 'Name',
 'Evolution',
 'Type',
 'Total',
 'HP',
 'Attack',
 'Defense',
 'Sp.Atk',
 'Sp.Def',
 'Speed',
 'Species',
 'Height',
 'Weight',
 'abilities',
 'ev_yield',
 'catch_rate',
 'base_friendship',
 'base_experience',
 'growth_rate',
 'eggs_groups',
 'gender_rate',
 'eggs_cycles_rate']

In [20]:
df.dtypes

Unnamed: 0          int64
Name                  str
Evolution             str
Type                  str
Total               int64
HP                  int64
Attack              int64
Defense             int64
Sp.Atk              int64
Sp.Def              int64
Speed               int64
Species               str
Height                str
Weight                str
abilities             str
ev_yield              str
catch_rate            str
base_friendship       str
base_experience     int64
growth_rate           str
eggs_groups           str
gender_rate           str
eggs_cycles_rate      str
dtype: object

In [21]:
df.describe()

,Unnamed: 0,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,Speed,base_experience
count,1045.000000,1045.000000,1045.000000,1045.000000,1045.000000,1045.000000,1045.000000,1045.000000,1045.000000
mean,522.000000,439.314833,70.067943,80.466986,74.661244,73.022010,72.288995,68.807656,152.729187
std,301.809819,121.970701,26.671411,32.413665,31.237903,32.724797,28.074148,30.210094,77.323984
min,0.000000,175.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,36.000000
25%,261.000000,330.000000,50.000000,55.000000,50.000000,50.000000,50.000000,45.000000,67.000000
50%,522.000000,458.000000,68.000000,77.000000,70.000000,65.000000,70.000000,65.000000,159.000000
75%,783.000000,515.000000,82.000000,100.000000,90.000000,95.000000,90.000000,90.000000,185.000000
max,1044.000000,1125.000000,255.000000,190.000000,250.000000,194.000000,250.000000,200.000000,608.000000

In [22]:
df.isnull().sum

<bound method DataFrame.sum of       Unnamed: 0   Name  Evolution   Type  Total     HP  Attack  Defense  \
0          False  False      False  False  False  False   False    False
1          False  False      False  False  False  False   False    False
2          False  False      False  False  False  False   False    False
3          False  False      False  False  False  False   False    False
4          False  False      False  False  False  False   False    False
...          ...    ...        ...    ...    ...    ...     ...      ...
1040       False  False      False  False  False  False   False    False
1041       False  False      False  False  False  False   False    False
1042       False  False      False  False  False  False   False    False
1043       False  False      False  False  False  False   False    False
1044       False  False      False  False  False  False   False    False

      Sp.Atk  Sp.Def  ...  Weight  abilities  ev_yield  catch_rate  \
0      False   False  ...   False      False     False       False
1      False   False  ...   False      False     False       False
2      False   False  ...   False      False     False       False
3      False   False  ...   False      False     False       False
4      False   False  ...   False      False     False       False
...      ...     ...  ...     ...        ...       ...         ...
1040   False   False  ...   False      False     False       False
1041   False   False  ...   False      False     False       False
1042   False   False  ...   False      False     False       False
1043   False   False  ...   False      False     False       False
1044   False   False  ...   False      False     False       False

      base_friendship  base_experience  growth_rate  eggs_groups  gender_rate  \
0               False            False        False        False        False
1               False            False        False        False        False
2               False            False        False        False        False
3               False            False        False        False        False
4               False            False        False        False        False
...               ...              ...          ...          ...          ...
1040            False            False        False        False        False
1041            False            False        False        False        False
1042            False            False        False        False        False
1043            False            False        False        False        False
1044            False            False        False        False        False

      eggs_cycles_rate
0                False
1                False
2                False
3                False
4                False
...                ...
1040             False
1041             False
1042             False
1043             False
1044             False

[1045 rows x 23 columns]>

In [23]:
df['Sp.Atk'].nunique()

119